# Generated by Django 2.2.3 on 2019-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
