# Generated by Django 2.2.3 on 2019-07-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0003_auto_20190723_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
